project:
  type: website

website:
  title: "Posit Team"
  navbar:
    left:
      - href: index.qmd
        text: Tutorials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

editor: visual

